version: "3.7"
services:
  # db:
  #   image: mysql
  #   command: '--default-authentication-plugin=mysql_native_password'
  #   restart: always
  #   ports:
  #     - 3306:3306
  #   volumes:
  #     - .:/shared
  #     # - ./mysql-data:/var/lib/mysql
  #   environment:
  #     - MYSQL_DATABASE=video_store
  #     - MYSQL_ROOT_PASSWORD=password

  postgres:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - .:/shared
      - ./postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      # - ./pg-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=video_store
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password

  # mssql:
  #   image: mcr.microsoft.com/mssql/server
  #   ports:
  #     - "1433:1433"
  #   restart: always
  #   entrypoint: /opt/mssql/bin/sqlservr
  #   environment:
  #     - SA_PASSWORD=P4s5w0rd%)~complex!
  #     - ACCEPT_EULA=Y