.DEFAULT_GOAL := help

.PHONY: help
help: ## Help
	@grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | sort | awk 'BEGIN {FS = ":.*?## "}; {printf "\033[36m%-30s\033[0m %s\n", $$1, $$2}'

# TODO: specific test

.PHONY: test
test: ## run all tests
	docker build -t sqlite-test-runner . \
	&& \
	docker run --rm sqlite-test-runner sh
